function [domain2D] = DomainCoupling2D(lx, ly,...
    gcoord, nodes_bound, nodes_interface,...
    origin, boundary_type, source)

    if nargin == 7
        source = models.SourceModelNone();
    end
    
    if isempty(nodes_interface)
        dtype = models.DomainType.NoCoupling;
    else
        dtype = models.DomainType.WBCoupling;
    end
    
    domain2D = struct(...
        'type', dtype,...
        'lx', lx,...
        'ly', ly,...
        'gcoord', gcoord,...
        'nodes_bound', nodes_bound,...
        'nodes_interface', nodes_interface,...
        'origin', origin,...
        'boundary_type', boundary_type,... % only support for the same boundary type in the whole domain 
        'source', source);
end