function [domain2D] = Domain2D(bbox,mesh,source,etov,boundary_type,bound_detec_f,bound_cond_f)
%ACOUSTICPARAMETERS Initialize a Domain2D struct

    domain2D = struct(...
        'bounding_box', bbox,...
        'boundary_type', boundary_type,... % only support for the same boundary type in the whole domain 
        'mesh', mesh,...
        'source', source,...
        'etov', etov,...
        'bound_detect_f', bound_detec_f,...
        'bound_cond_f', bound_cond_f);
end