function [mesh2D] = Mesh2D(XY,bbox,etov,bound_detec_f)
%ACOUSTICPARAMETERS Initialize a Domain2D struct

    mesh2D = struct(...
        'XY', XY,...
        'bbox', bbox,...
        'etov', etov,...
        'bound_detect_f', bound_detec_f);
end