function [pointSource2D] = SourceModel(type, r0, F, dF)
%POINTSOURCE Initialize a PointSource struct

    pointSource2D = struct(...
        'type', type,...
        'r0', r0,...
        'F', F,...
        'dF', dF);
end